### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by nason** [ReadUpCode/readup#126]
Cloned down my fork and there's no build instructions to be found!  I'll write some up as I setup my dev environment and will submit them for review.

**Comment by nason** [comment]
Actually, I have no clue what some of the environment variables are for at first glance, so maybe one of the ReadUp team can fill this in. Here's my outline that the build instructions could start from:

#### Build Instructions:
1. `npm install`
2. Import MySQL seed file
3. Setup environment variables
4. Run tests
5. Start server with `grunt`

**Comment by blakewest** [comment]
This has been taken care of with a cloud hosted MySQL database, and a start script that handles the build process. The ReadMe has been updated to reflect all this, and gives the instructions necessary. Build process should be very smooth now.
