### ISSUE TITLE
Build results in incomplete app

### ISSUE THREAD

**Issue by rps** [ReadUpCode/readup#140]
App may be missing some dependencies, as the rendering on localhost fails.

**Comment by blakewest** [comment]
Rich, is this still an issue? I believe if you follow the build instructions in the ReadMe, and run the start script, then it should set everything up for you, and allow you to go to localhost:3000 and see ReadUp correctly. If not, then write down exactly what your process was so we can try to reproduce the error and fix it.

**Comment by stangah** [comment]
Did the grunt file get changed to compile on start?

**Comment by rps** [comment]
Seems to work today. Not sure whether this is related to caching or what.
